"""Domain rules package (S0-SIM-001 + S3-RULES-001/002/003)."""

from fictional_world.domain.rules.combat import (
    CombatantSnapshot,
    CombatExchangeInput,
    CombatExchangeResult,
    CombatOutcomeClass,
    combatant_score,
    feasible_outcome_envelope,
    resolve_combat_exchange,
)
from fictional_world.domain.rules.effects import (
    EffectValidationContext,
    project_effect,
    validate_effect,
    validate_effects,
)
from fictional_world.domain.rules.injuries import (
    BodyRegion,
    DeathValidationContext,
    InjuryApplication,
    InjuryState,
    InjuryType,
    LifeStatus,
    RecoveryStep,
    ReturnFromDeathContext,
    apply_injury,
    injury_action_penalty,
    progress_recovery,
    validate_death_prerequisites,
    validate_return_from_death,
)
from fictional_world.domain.rules.invariants import INVARIANT_REGISTRY, get_invariant
from fictional_world.domain.rules.magic import (
    CastTimeClass,
    KnownSpell,
    MagicState,
    SpellAttempt,
    SpellDefinition,
    SpellOutcomeClass,
    SpellPrerequisites,
    SpellResolution,
    SpellTargetRules,
    resolve_spell_attempt,
    validate_spell_prerequisites,
)
from fictional_world.domain.rules.phase_transitions import (
    PHASE_STAGE_ORDER,
    SCENE_STAGE_ORDER,
    assert_phase_stage_advance,
    assert_run_status_transition,
    assert_scene_stage_advance,
)
from fictional_world.domain.rules.scale import STAT_MAX, STAT_MIN, clamp_unit, clamp_world_scale
from fictional_world.domain.rules.seeded import SeededRng, mix_seed, seeded_unit_float
from fictional_world.domain.rules.skills import (
    SkillProgressEvidence,
    SkillProgressProposal,
    SkillState,
    accumulate_skill_evidence,
    apply_skill_progress,
    propose_skill_progress,
)
from fictional_world.domain.rules.stats import (
    CapabilityKind,
    DerivedCapabilityInputs,
    EffectiveStat,
    StatEvidence,
    StatState,
    StatType,
    TemporaryModifier,
    apply_stat_evidence,
    clamp_stat,
    compute_derived_capability,
    effective_stat,
)

__all__ = [
    "INVARIANT_REGISTRY",
    "PHASE_STAGE_ORDER",
    "SCENE_STAGE_ORDER",
    "STAT_MAX",
    "STAT_MIN",
    "BodyRegion",
    "CapabilityKind",
    "CastTimeClass",
    "CombatExchangeInput",
    "CombatExchangeResult",
    "CombatOutcomeClass",
    "CombatantSnapshot",
    "DeathValidationContext",
    "DerivedCapabilityInputs",
    "EffectValidationContext",
    "EffectiveStat",
    "InjuryApplication",
    "InjuryState",
    "InjuryType",
    "KnownSpell",
    "LifeStatus",
    "MagicState",
    "RecoveryStep",
    "ReturnFromDeathContext",
    "SeededRng",
    "SkillProgressEvidence",
    "SkillProgressProposal",
    "SkillState",
    "SpellAttempt",
    "SpellDefinition",
    "SpellOutcomeClass",
    "SpellPrerequisites",
    "SpellResolution",
    "SpellTargetRules",
    "StatEvidence",
    "StatState",
    "StatType",
    "TemporaryModifier",
    "accumulate_skill_evidence",
    "apply_injury",
    "apply_skill_progress",
    "apply_stat_evidence",
    "assert_phase_stage_advance",
    "assert_run_status_transition",
    "assert_scene_stage_advance",
    "clamp_stat",
    "clamp_unit",
    "clamp_world_scale",
    "combatant_score",
    "compute_derived_capability",
    "effective_stat",
    "feasible_outcome_envelope",
    "get_invariant",
    "injury_action_penalty",
    "mix_seed",
    "progress_recovery",
    "project_effect",
    "propose_skill_progress",
    "resolve_combat_exchange",
    "resolve_spell_attempt",
    "seeded_unit_float",
    "validate_death_prerequisites",
    "validate_effect",
    "validate_effects",
    "validate_return_from_death",
    "validate_spell_prerequisites",
]
