"""Export worldsim schema DDL snapshot for docs/generated."""

from __future__ import annotations

import argparse
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "docs" / "generated" / "database-schema.sql"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--database-url",
        default=os.environ.get("ALEMBIC_DATABASE_URL")
        or os.environ.get("DATABASE_URL")
        or "postgresql://fictional_world:change-me-local@127.0.0.1:5432/fictional_world",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    # Normalize SQLAlchemy URLs to plain postgres for pg_dump
    url = args.database_url.replace("postgresql+psycopg://", "postgresql://").replace(
        "postgresql+psycopg2://", "postgresql://"
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "docker",
        "compose",
        "exec",
        "-T",
        "postgres",
        "pg_dump",
        "--schema=worldsim",
        "--schema-only",
        "--no-owner",
        "--no-privileges",
        "-U",
        "fictional_world",
        "fictional_world",
    ]
    # Prefer local pg_dump if DATABASE is reachable without docker; else compose.
    try:
        completed = subprocess.run(
            [
                "pg_dump",
                url,
                "--schema=worldsim",
                "--schema-only",
                "--no-owner",
                "--no-privileges",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        ddl = completed.stdout
    except (FileNotFoundError, subprocess.CalledProcessError):
        completed = subprocess.run(cmd, check=True, cwd=ROOT, capture_output=True, text=True)
        ddl = completed.stdout

    header = (
        "-- Generated by scripts/export_database_schema.py - do not hand-edit.\n"
        "-- Schema: worldsim (through 0004_stage2_continuity_tables)\n\n"
    )
    cleaned_lines = [
        line
        for line in ddl.splitlines(keepends=True)
        if not line.startswith("\\restrict") and not line.startswith("\\unrestrict")
    ]
    args.output.write_text(header + "".join(cleaned_lines), encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
