"""Create Stage 0 core worldsim tables.

Revision ID: 0002_core_stage0_tables
Revises: 0001_extensions_and_schema
Create Date: 2026-07-29
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0002_core_stage0_tables"
down_revision: str | None = "0001_extensions_and_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_profile",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_key", sa.Text(), nullable=False),
        sa.Column("logical_role", sa.Text(), nullable=False),
        sa.Column("provider_adapter", sa.Text(), nullable=False),
        sa.Column("model_slug", sa.Text(), nullable=False),
        sa.Column("endpoint_type", sa.Text(), nullable=False),
        sa.Column("context_limit", sa.Integer(), nullable=False),
        sa.Column("application_input_limit", sa.Integer(), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "sampling_configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("structured_output_required", sa.Boolean(), nullable=False),
        sa.Column("privacy_classification", sa.Text(), nullable=False),
        sa.Column("capability_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "active_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("active_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "application_input_limit > 0", name=op.f("ck_model_profile_app_input_limit_positive")
        ),
        sa.CheckConstraint(
            "context_limit > 0", name=op.f("ck_model_profile_context_limit_positive")
        ),
        sa.CheckConstraint(
            "max_output_tokens >= 0", name=op.f("ck_model_profile_max_output_nonneg")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_profile")),
        sa.UniqueConstraint("profile_key", name=op.f("uq_model_profile_profile_key")),
        schema="worldsim",
    )
    op.create_table(
        "world",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), server_default=sa.text("'en'"), nullable=False),
        sa.Column(
            "content_rating",
            sa.Text(),
            server_default=sa.text("'young_adult_soft_dark'"),
            nullable=False,
        ),
        sa.Column(
            "current_event_sequence", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("version", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'ended' AND ended_at IS NOT NULL) OR (status <> 'ended')",
            name=op.f("ck_world_ended_status_consistency"),
        ),
        sa.CheckConstraint(
            "status IN ('initializing', 'active', 'paused', 'ended', 'archived')",
            name=op.f("ck_world_status"),
        ),
        sa.CheckConstraint(
            "current_event_sequence >= 0", name=op.f("ck_world_event_sequence_nonneg")
        ),
        sa.CheckConstraint("version >= 0", name=op.f("ck_world_version_nonneg")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_world")),
        sa.UniqueConstraint("slug", name=op.f("uq_world_slug")),
        schema="worldsim",
    )
    op.create_index(
        "uq_world_one_live",
        "world",
        [sa.literal_column("(true)")],
        unique=True,
        schema="worldsim",
        postgresql_where=sa.text("status IN ('initializing', 'active', 'paused')"),
    )
    op.create_table(
        "aggregate_version",
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_type", sa.Text(), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 0", name=op.f("ck_aggregate_version_version_nonneg")),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_aggregate_version_world_id_world")
        ),
        sa.PrimaryKeyConstraint(
            "world_id", "aggregate_type", "aggregate_id", name=op.f("pk_aggregate_version")
        ),
        schema="worldsim",
    )
    op.create_table(
        "entity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("lifecycle_status", sa.Text(), nullable=False),
        sa.Column("created_event_id", sa.Uuid(), nullable=True),
        sa.Column("archived_event_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["archived_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_entity_archived_event_id_world_event"),
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_entity_created_event_id_world_event"),
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_entity_world_id_world")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity")),
        schema="worldsim",
    )
    op.create_index(
        "ix_entity_world_lifecycle",
        "entity",
        ["world_id", "lifecycle_status"],
        unique=False,
        schema="worldsim",
    )
    op.create_index(
        "ix_entity_world_type_name",
        "entity",
        ["world_id", "entity_type", "normalized_name"],
        unique=False,
        schema="worldsim",
    )
    op.create_table(
        "phase_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("absolute_phase_index", sa.BigInteger(), nullable=False),
        sa.Column("phase_name", sa.Text(), nullable=False),
        sa.Column("resolution_mode", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("expected_character_count", sa.SmallInteger(), nullable=False),
        sa.Column(
            "completed_character_count",
            sa.SmallInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("expected_scene_count", sa.SmallInteger(), nullable=True),
        sa.Column(
            "completed_scene_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("request_reservation_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "resolution_mode IN ('detailed', 'day', 'week', 'month', 'year')",
            name=op.f("ck_phase_run_resolution_mode"),
        ),
        sa.CheckConstraint(
            "absolute_phase_index >= 0", name=op.f("ck_phase_run_absolute_phase_nonneg")
        ),
        sa.CheckConstraint(
            "completed_character_count >= 0", name=op.f("ck_phase_run_completed_character_nonneg")
        ),
        sa.CheckConstraint(
            "completed_scene_count >= 0", name=op.f("ck_phase_run_completed_scene_nonneg")
        ),
        sa.CheckConstraint(
            "expected_character_count >= 0", name=op.f("ck_phase_run_expected_character_nonneg")
        ),
        sa.CheckConstraint("version >= 0", name=op.f("ck_phase_run_version_nonneg")),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_phase_run_world_id_world")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phase_run")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_phase_run_idempotency_key")),
        sa.UniqueConstraint(
            "world_id",
            "absolute_phase_index",
            name=op.f("uq_phase_run_world_id_absolute_phase_index"),
        ),
        schema="worldsim",
    )
    op.create_index(
        "uq_phase_run_one_nonterminal_per_world",
        "phase_run",
        ["world_id"],
        unique=True,
        schema="worldsim",
        postgresql_where=sa.text("state NOT IN ('completed', 'failed', 'cancelled')"),
    )
    op.create_table(
        "world_clock",
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("generation_number", sa.SmallInteger(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.SmallInteger(), nullable=False),
        sa.Column("day", sa.SmallInteger(), nullable=False),
        sa.Column("phase_name", sa.Text(), nullable=False),
        sa.Column("phase_ordinal", sa.SmallInteger(), nullable=False),
        sa.Column("absolute_day_index", sa.BigInteger(), nullable=False),
        sa.Column("absolute_phase_index", sa.BigInteger(), nullable=False),
        sa.Column("resolution_mode", sa.Text(), nullable=False),
        sa.Column("last_event_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "phase_name IN ('dawn','sunrise','morning','noon','afternoon','sunset','dusk','evening','night','midnight') OR resolution_mode <> 'detailed'",
            name=op.f("ck_world_clock_detailed_phase_name"),
        ),
        sa.CheckConstraint(
            "resolution_mode IN ('detailed', 'day', 'week', 'month', 'year')",
            name=op.f("ck_world_clock_resolution_mode"),
        ),
        sa.CheckConstraint(
            "absolute_day_index >= 0", name=op.f("ck_world_clock_absolute_day_nonneg")
        ),
        sa.CheckConstraint(
            "absolute_phase_index >= 0", name=op.f("ck_world_clock_absolute_phase_nonneg")
        ),
        sa.CheckConstraint("day BETWEEN 1 AND 31", name=op.f("ck_world_clock_day_range")),
        sa.CheckConstraint(
            "generation_number BETWEEN 1 AND 3", name=op.f("ck_world_clock_generation_range")
        ),
        sa.CheckConstraint("month BETWEEN 1 AND 12", name=op.f("ck_world_clock_month_range")),
        sa.CheckConstraint(
            "phase_ordinal BETWEEN 0 AND 9", name=op.f("ck_world_clock_phase_ordinal_range")
        ),
        sa.CheckConstraint("version >= 0", name=op.f("ck_world_clock_version_nonneg")),
        sa.ForeignKeyConstraint(
            ["last_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_world_clock_last_event_id_world_event"),
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_world_clock_world_id_world")
        ),
        sa.PrimaryKeyConstraint("world_id", name=op.f("pk_world_clock")),
        schema="worldsim",
    )
    op.create_table(
        "world_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("effective_from_phase_index", sa.BigInteger(), nullable=False),
        sa.Column("detailed_phase_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_days", sa.Integer(), nullable=False),
        sa.Column(
            "max_generations", sa.SmallInteger(), server_default=sa.text("3"), nullable=False
        ),
        sa.Column("plot_armour_level", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("director_privileges", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("image_budget_per_day", sa.SmallInteger(), nullable=False),
        sa.Column(
            "macro_simulation_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("content_policy_version", sa.Text(), nullable=False),
        sa.Column("created_event_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "config_version >= 1", name=op.f("ck_world_config_config_version_positive")
        ),
        sa.CheckConstraint("max_days >= 1", name=op.f("ck_world_config_max_days_positive")),
        sa.CheckConstraint(
            "max_generations BETWEEN 1 AND 3", name=op.f("ck_world_config_max_generations_range")
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_world_config_created_event_id_world_event"),
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_world_config_world_id_world")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_world_config")),
        sa.UniqueConstraint(
            "world_id", "config_version", name=op.f("uq_world_config_world_id_config_version")
        ),
        schema="worldsim",
    )
    op.create_index(
        "uq_world_config_one_active",
        "world_config",
        ["world_id"],
        unique=True,
        schema="worldsim",
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "character",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("character_kind", sa.Text(), nullable=False),
        sa.Column("birth_event_id", sa.Uuid(), nullable=True),
        sa.Column("death_event_id", sa.Uuid(), nullable=True),
        sa.Column("birth_phase_index", sa.BigInteger(), nullable=True),
        sa.Column("death_phase_index", sa.BigInteger(), nullable=True),
        sa.Column("biological_age_days", sa.Integer(), nullable=True),
        sa.Column("species_code", sa.Text(), nullable=False),
        sa.Column("sex_or_body_profile", sa.Text(), nullable=True),
        sa.Column("current_card_version_id", sa.Uuid(), nullable=True),
        sa.Column("npc_persistence_until_day", sa.BigInteger(), nullable=True),
        sa.Column("version", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "character_kind IN ('focus', 'lineage', 'temporary_npc', 'recurring_npc')",
            name=op.f("ck_character_character_kind"),
        ),
        sa.CheckConstraint("version >= 0", name=op.f("ck_character_version_nonneg")),
        sa.ForeignKeyConstraint(
            ["current_card_version_id"],
            ["worldsim.character_card_version.id"],
            name=op.f("fk_character_current_card_version_id_character_card_version"),
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["worldsim.entity.id"], name=op.f("fk_character_entity_id_entity")
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_character")),
        schema="worldsim",
    )
    op.create_table(
        "location",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("parent_location_id", sa.Uuid(), nullable=True),
        sa.Column("location_type", sa.Text(), nullable=False),
        sa.Column("region_code", sa.Text(), nullable=False),
        sa.Column("coordinate_x", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("coordinate_y", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("elevation", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("owner_entity_id", sa.Uuid(), nullable=True),
        sa.Column("environment_tags", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("canonical_description", sa.Text(), nullable=False),
        sa.Column(
            "visual_profile_version", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["worldsim.entity.id"], name=op.f("fk_location_entity_id_entity")
        ),
        sa.ForeignKeyConstraint(
            ["owner_entity_id"],
            ["worldsim.entity.id"],
            name=op.f("fk_location_owner_entity_id_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_location_id"],
            ["worldsim.location.entity_id"],
            name=op.f("fk_location_parent_location_id_location"),
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_location")),
        schema="worldsim",
    )
    op.create_table(
        "phase_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("phase_run_id", sa.Uuid(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("source_event_sequence", sa.BigInteger(), nullable=False),
        sa.Column("world_clock_version", sa.BigInteger(), nullable=False),
        sa.Column("state_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state_hash", sa.Text(), nullable=False),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["phase_run_id"],
            ["worldsim.phase_run.id"],
            name=op.f("fk_phase_snapshot_phase_run_id_phase_run"),
        ),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_phase_snapshot_world_id_world")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phase_snapshot")),
        sa.UniqueConstraint("phase_run_id", name=op.f("uq_phase_snapshot_phase_run_id")),
        schema="worldsim",
    )
    op.create_table(
        "task_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_type", sa.Text(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=True),
        sa.Column("phase_run_id", sa.Uuid(), nullable=True),
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("subject_entity_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("attempt_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), server_default=sa.text("3"), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_reference", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_task_run_attempt_count_nonneg")),
        sa.CheckConstraint("max_attempts >= 1", name=op.f("ck_task_run_max_attempts_positive")),
        sa.CheckConstraint("priority >= 0", name=op.f("ck_task_run_priority_nonneg")),
        sa.ForeignKeyConstraint(
            ["phase_run_id"],
            ["worldsim.phase_run.id"],
            name=op.f("fk_task_run_phase_run_id_phase_run"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_entity_id"],
            ["worldsim.entity.id"],
            name=op.f("fk_task_run_subject_entity_id_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_task_run_world_id_world")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_run")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_task_run_idempotency_key")),
        schema="worldsim",
    )
    op.create_table(
        "character_card_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("identity", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("backstory", sa.Text(), nullable=False),
        sa.Column("appearance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("personality_traits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fears", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("desires", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("boundaries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("voice_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("initial_capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("secret_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("source_event_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_character_card_version_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["worldsim.character.entity_id"],
            name=op.f("fk_character_card_version_character_id_character"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_card_version")),
        sa.UniqueConstraint(
            "character_id",
            "content_hash",
            name=op.f("uq_character_card_version_character_id_content_hash"),
        ),
        sa.UniqueConstraint(
            "character_id",
            "version_number",
            name=op.f("uq_character_card_version_character_id_version_number"),
        ),
        schema="worldsim",
    )
    op.create_table(
        "model_call",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=True),
        sa.Column("phase_run_id", sa.Uuid(), nullable=True),
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("character_id", sa.Uuid(), nullable=True),
        sa.Column("task_run_id", sa.Uuid(), nullable=True),
        sa.Column("model_profile_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("context_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("response_hash", sa.Text(), nullable=True),
        sa.Column("provider_request_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempt_number", sa.SmallInteger(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("raw_request_object_key", sa.Text(), nullable=True),
        sa.Column("raw_response_object_key", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("attempt_number >= 1", name=op.f("ck_model_call_attempt_positive")),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["worldsim.character.entity_id"],
            name=op.f("fk_model_call_character_id_character"),
        ),
        sa.ForeignKeyConstraint(
            ["model_profile_id"],
            ["worldsim.model_profile.id"],
            name=op.f("fk_model_call_model_profile_id_model_profile"),
        ),
        sa.ForeignKeyConstraint(
            ["phase_run_id"],
            ["worldsim.phase_run.id"],
            name=op.f("fk_model_call_phase_run_id_phase_run"),
        ),
        sa.ForeignKeyConstraint(
            ["task_run_id"],
            ["worldsim.task_run.id"],
            name=op.f("fk_model_call_task_run_id_task_run"),
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_model_call_world_id_world")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_call")),
        schema="worldsim",
    )
    op.create_table(
        "request_budget_ledger",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reservation_key", sa.Text(), nullable=False),
        sa.Column("required_request_count", sa.Integer(), nullable=False),
        sa.Column("provider_kind", sa.Text(), nullable=False),
        sa.Column("model_slug", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=True),
        sa.Column("phase_run_id", sa.Uuid(), nullable=True),
        sa.Column("task_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "reserved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('reserved', 'consumed', 'released', 'expired')",
            name=op.f("ck_request_budget_ledger_budget_status"),
        ),
        sa.CheckConstraint(
            "required_request_count >= 1",
            name=op.f("ck_request_budget_ledger_required_count_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["phase_run_id"],
            ["worldsim.phase_run.id"],
            name=op.f("fk_request_budget_ledger_phase_run_id_phase_run"),
        ),
        sa.ForeignKeyConstraint(
            ["task_run_id"],
            ["worldsim.task_run.id"],
            name=op.f("fk_request_budget_ledger_task_run_id_task_run"),
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worldsim.world.id"],
            name=op.f("fk_request_budget_ledger_world_id_world"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_budget_ledger")),
        sa.UniqueConstraint(
            "reservation_key", name=op.f("uq_request_budget_ledger_reservation_key")
        ),
        schema="worldsim",
    )
    op.create_table(
        "task_dependency",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("depends_on_task_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "task_id <> depends_on_task_id", name=op.f("ck_task_dependency_no_self_dependency")
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_task_id"],
            ["worldsim.task_run.id"],
            name=op.f("fk_task_dependency_depends_on_task_id_task_run"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["worldsim.task_run.id"], name=op.f("fk_task_dependency_task_id_task_run")
        ),
        sa.PrimaryKeyConstraint("task_id", "depends_on_task_id", name=op.f("pk_task_dependency")),
        schema="worldsim",
    )
    op.create_table(
        "world_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_number", sa.BigInteger(), nullable=False),
        sa.Column("absolute_phase_index", sa.BigInteger(), nullable=False),
        sa.Column("phase_run_id", sa.Uuid(), nullable=True),
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("initiator_entity_id", sa.Uuid(), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("canonical_summary", sa.Text(), nullable=False),
        sa.Column("structured_facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("importance", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("visibility_class", sa.Text(), nullable=False),
        sa.Column("source_kind", sa.Text(), nullable=False),
        sa.Column("source_model_profile_id", sa.Uuid(), nullable=True),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("random_seed", sa.BigInteger(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("supersedes_event_id", sa.Uuid(), nullable=True),
        sa.Column("consistency_status", sa.Text(), nullable=False),
        sa.Column(
            "committed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "absolute_phase_index >= 0", name=op.f("ck_world_event_absolute_phase_nonneg")
        ),
        sa.CheckConstraint(
            "importance >= 0 AND importance <= 1", name=op.f("ck_world_event_importance_range")
        ),
        sa.CheckConstraint("sequence_number >= 1", name=op.f("ck_world_event_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["initiator_entity_id"],
            ["worldsim.entity.id"],
            name=op.f("fk_world_event_initiator_entity_id_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["worldsim.location.entity_id"],
            name=op.f("fk_world_event_location_id_location"),
        ),
        sa.ForeignKeyConstraint(
            ["phase_run_id"],
            ["worldsim.phase_run.id"],
            name=op.f("fk_world_event_phase_run_id_phase_run"),
        ),
        sa.ForeignKeyConstraint(
            ["source_model_profile_id"],
            ["worldsim.model_profile.id"],
            name=op.f("fk_world_event_source_model_profile_id_model_profile"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_world_event_supersedes_event_id_world_event"),
        ),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_world_event_world_id_world")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_world_event")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_world_event_idempotency_key")),
        sa.UniqueConstraint(
            "world_id", "sequence_number", name=op.f("uq_world_event_world_id_sequence_number")
        ),
        schema="worldsim",
    )
    op.create_index(
        "ix_world_event_timeline",
        "world_event",
        ["world_id", "absolute_phase_index", "sequence_number"],
        unique=False,
        schema="worldsim",
    )
    op.create_index(
        "ix_world_event_type", "world_event", ["event_type"], unique=False, schema="worldsim"
    )
    op.create_table(
        "character_state",
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("life_status", sa.Text(), nullable=False),
        sa.Column("stamina", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("mana", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("energy", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("hunger", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("pain", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("stress", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("social_need", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("valence", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("arousal", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("dominance", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("active_activity_id", sa.Uuid(), nullable=True),
        sa.Column("current_card_version_id", sa.Uuid(), nullable=False),
        sa.Column("last_source_event_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "arousal BETWEEN 0 AND 1", name=op.f("ck_character_state_arousal_range")
        ),
        sa.CheckConstraint(
            "dominance BETWEEN -1 AND 1", name=op.f("ck_character_state_dominance_range")
        ),
        sa.CheckConstraint(
            "energy BETWEEN 0 AND 100", name=op.f("ck_character_state_energy_range")
        ),
        sa.CheckConstraint(
            "hunger BETWEEN 0 AND 100", name=op.f("ck_character_state_hunger_range")
        ),
        sa.CheckConstraint("mana BETWEEN 0 AND 100", name=op.f("ck_character_state_mana_range")),
        sa.CheckConstraint("pain BETWEEN 0 AND 100", name=op.f("ck_character_state_pain_range")),
        sa.CheckConstraint(
            "social_need BETWEEN 0 AND 100", name=op.f("ck_character_state_social_need_range")
        ),
        sa.CheckConstraint(
            "stamina BETWEEN 0 AND 100", name=op.f("ck_character_state_stamina_range")
        ),
        sa.CheckConstraint(
            "stress BETWEEN 0 AND 100", name=op.f("ck_character_state_stress_range")
        ),
        sa.CheckConstraint(
            "valence BETWEEN -1 AND 1", name=op.f("ck_character_state_valence_range")
        ),
        sa.CheckConstraint("version >= 0", name=op.f("ck_character_state_version_nonneg")),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["worldsim.character.entity_id"],
            name=op.f("fk_character_state_character_id_character"),
        ),
        sa.ForeignKeyConstraint(
            ["current_card_version_id"],
            ["worldsim.character_card_version.id"],
            name=op.f("fk_character_state_current_card_version_id_character_card_version"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["worldsim.location.entity_id"],
            name=op.f("fk_character_state_location_id_location"),
        ),
        sa.PrimaryKeyConstraint("character_id", name=op.f("pk_character_state")),
        schema="worldsim",
    )
    op.create_table(
        "event_effect",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_event_id", sa.Uuid(), nullable=False),
        sa.Column("effect_index", sa.SmallInteger(), nullable=False),
        sa.Column("effect_type", sa.Text(), nullable=False),
        sa.Column("target_entity_id", sa.Uuid(), nullable=True),
        sa.Column("effect_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("previous_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resulting_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_version_before", sa.BigInteger(), nullable=True),
        sa.Column("target_version_after", sa.BigInteger(), nullable=True),
        sa.Column("source_attempt_ids", postgresql.ARRAY(sa.Uuid()), nullable=True),
        sa.Column("validation_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("effect_index >= 0", name=op.f("ck_event_effect_effect_index_nonneg")),
        sa.ForeignKeyConstraint(
            ["target_entity_id"],
            ["worldsim.entity.id"],
            name=op.f("fk_event_effect_target_entity_id_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["world_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_event_effect_world_event_id_world_event"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_effect")),
        sa.UniqueConstraint(
            "world_event_id",
            "effect_index",
            name=op.f("uq_event_effect_world_event_id_effect_index"),
        ),
        schema="worldsim",
    )
    op.create_table(
        "observation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_event_id", sa.Uuid(), nullable=False),
        sa.Column("observer_id", sa.Uuid(), nullable=False),
        sa.Column("observation_type", sa.Text(), nullable=False),
        sa.Column("perceived_summary", sa.Text(), nullable=False),
        sa.Column("perceived_facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("omitted_fact_keys", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("visibility_reason", sa.Text(), nullable=False),
        sa.Column("source_sense_tags", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_observation_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["observer_id"],
            ["worldsim.character.entity_id"],
            name=op.f("fk_observation_observer_id_character"),
        ),
        sa.ForeignKeyConstraint(
            ["world_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_observation_world_event_id_world_event"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observation")),
        sa.UniqueConstraint(
            "world_event_id",
            "observer_id",
            "observation_type",
            "content_hash",
            name=op.f("uq_observation_world_event_id_observer_id_observation_type_content_hash"),
        ),
        schema="worldsim",
    )
    op.create_index(
        "ix_observation_observer_created",
        "observation",
        ["observer_id", "created_at"],
        unique=False,
        schema="worldsim",
    )
    op.create_index(
        "ix_observation_observer_event",
        "observation",
        ["observer_id", "world_event_id"],
        unique=False,
        schema="worldsim",
    )
    op.create_table(
        "outbox_message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_event_id", sa.Uuid(), nullable=True),
        sa.Column("message_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("attempt_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("claimed_by", sa.Text(), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_outbox_message_attempt_count_nonneg")
        ),
        sa.ForeignKeyConstraint(
            ["world_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_outbox_message_world_event_id_world_event"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_message")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_outbox_message_idempotency_key")),
        schema="worldsim",
    )
    op.create_table(
        "phase_snapshot_character",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.Column("character_state_version", sa.BigInteger(), nullable=False),
        sa.Column("card_version_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("active_activity_id", sa.Uuid(), nullable=True),
        sa.Column("context_source_hash", sa.Text(), nullable=False),
        sa.Column("eligibility_status", sa.Text(), nullable=False),
        sa.Column("eligibility_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_version_id"],
            ["worldsim.character_card_version.id"],
            name=op.f("fk_phase_snapshot_character_card_version_id_character_card_version"),
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["worldsim.character.entity_id"],
            name=op.f("fk_phase_snapshot_character_character_id_character"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["worldsim.location.entity_id"],
            name=op.f("fk_phase_snapshot_character_location_id_location"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["worldsim.phase_snapshot.id"],
            name=op.f("fk_phase_snapshot_character_snapshot_id_phase_snapshot"),
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_id", "character_id", name=op.f("pk_phase_snapshot_character")
        ),
        schema="worldsim",
    )
    op.create_table(
        "user_command",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("actor_role", sa.Text(), nullable=False),
        sa.Column("command_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_entity_id", sa.Uuid(), nullable=True),
        sa.Column("requested_phase_boundary", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("permission_decision", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("resulting_event_id", sa.Uuid(), nullable=True),
        sa.Column("resulting_task_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["resulting_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_user_command_resulting_event_id_world_event"),
        ),
        sa.ForeignKeyConstraint(
            ["resulting_task_id"],
            ["worldsim.task_run.id"],
            name=op.f("fk_user_command_resulting_task_id_task_run"),
        ),
        sa.ForeignKeyConstraint(
            ["target_entity_id"],
            ["worldsim.entity.id"],
            name=op.f("fk_user_command_target_entity_id_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_user_command_world_id_world")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_command")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_user_command_idempotency_key")),
        schema="worldsim",
    )
    op.create_table(
        "recent_memory",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("owner_character_id", sa.Uuid(), nullable=False),
        sa.Column("memory_type", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("salience", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("emotional_weight", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("visibility", sa.Text(), nullable=False),
        sa.Column("occurred_phase_index", sa.BigInteger(), nullable=False),
        sa.Column("created_phase_index", sa.BigInteger(), nullable=False),
        sa.Column("last_recalled_phase_index", sa.BigInteger(), nullable=True),
        sa.Column("recall_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("decay_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("summary_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("source_event_id", sa.Uuid(), nullable=True),
        sa.Column("source_observation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_recent_memory_confidence_range")
        ),
        sa.CheckConstraint(
            "decay_score >= 0 AND decay_score <= 1", name=op.f("ck_recent_memory_decay_score_range")
        ),
        sa.CheckConstraint(
            "emotional_weight >= 0 AND emotional_weight <= 1",
            name=op.f("ck_recent_memory_emotional_weight_range"),
        ),
        sa.CheckConstraint("recall_count >= 0", name=op.f("ck_recent_memory_recall_count_nonneg")),
        sa.CheckConstraint(
            "salience >= 0 AND salience <= 1", name=op.f("ck_recent_memory_salience_range")
        ),
        sa.CheckConstraint(
            "summary_version >= 1", name=op.f("ck_recent_memory_summary_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["owner_character_id"],
            ["worldsim.character.entity_id"],
            name=op.f("fk_recent_memory_owner_character_id_character"),
        ),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_recent_memory_source_event_id_world_event"),
        ),
        sa.ForeignKeyConstraint(
            ["source_observation_id"],
            ["worldsim.observation.id"],
            name=op.f("fk_recent_memory_source_observation_id_observation"),
        ),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_recent_memory_world_id_world")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recent_memory")),
        sa.UniqueConstraint(
            "owner_character_id",
            "content_hash",
            "summary_version",
            name=op.f("uq_recent_memory_owner_character_id_content_hash_summary_version"),
        ),
        schema="worldsim",
    )
    op.create_index(
        "ix_recent_memory_owner_created",
        "recent_memory",
        ["owner_character_id", "created_at"],
        unique=False,
        schema="worldsim",
    )
    op.create_index(
        "ix_recent_memory_world_owner",
        "recent_memory",
        ["world_id", "owner_character_id"],
        unique=False,
        schema="worldsim",
    )
    # Deferred FKs (use_alter cycles / forward references)
    op.create_foreign_key(
        op.f("fk_character_current_card_version_id_character_card_version"),
        "character",
        "character_card_version",
        ["current_card_version_id"],
        ["id"],
        source_schema="worldsim",
        referent_schema="worldsim",
    )
    op.create_foreign_key(
        op.f("fk_entity_created_event_id_world_event"),
        "entity",
        "world_event",
        ["created_event_id"],
        ["id"],
        source_schema="worldsim",
        referent_schema="worldsim",
    )
    op.create_foreign_key(
        op.f("fk_entity_archived_event_id_world_event"),
        "entity",
        "world_event",
        ["archived_event_id"],
        ["id"],
        source_schema="worldsim",
        referent_schema="worldsim",
    )
    op.create_foreign_key(
        op.f("fk_model_call_task_run_id_task_run"),
        "model_call",
        "task_run",
        ["task_run_id"],
        ["id"],
        source_schema="worldsim",
        referent_schema="worldsim",
    )
    op.create_foreign_key(
        op.f("fk_world_clock_last_event_id_world_event"),
        "world_clock",
        "world_event",
        ["last_event_id"],
        ["id"],
        source_schema="worldsim",
        referent_schema="worldsim",
    )
    op.create_foreign_key(
        op.f("fk_world_config_created_event_id_world_event"),
        "world_config",
        "world_event",
        ["created_event_id"],
        ["id"],
        source_schema="worldsim",
        referent_schema="worldsim",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_world_config_created_event_id_world_event"),
        "world_config",
        schema="worldsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_world_clock_last_event_id_world_event"),
        "world_clock",
        schema="worldsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_model_call_task_run_id_task_run"),
        "model_call",
        schema="worldsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_entity_archived_event_id_world_event"),
        "entity",
        schema="worldsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_entity_created_event_id_world_event"),
        "entity",
        schema="worldsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_character_current_card_version_id_character_card_version"),
        "character",
        schema="worldsim",
        type_="foreignkey",
    )
    op.drop_index("ix_recent_memory_world_owner", table_name="recent_memory", schema="worldsim")
    op.drop_index("ix_recent_memory_owner_created", table_name="recent_memory", schema="worldsim")
    op.drop_table("recent_memory", schema="worldsim")
    op.drop_table("user_command", schema="worldsim")
    op.drop_table("phase_snapshot_character", schema="worldsim")
    op.drop_table("outbox_message", schema="worldsim")
    op.drop_index("ix_observation_observer_event", table_name="observation", schema="worldsim")
    op.drop_index("ix_observation_observer_created", table_name="observation", schema="worldsim")
    op.drop_table("observation", schema="worldsim")
    op.drop_table("event_effect", schema="worldsim")
    op.drop_table("character_state", schema="worldsim")
    op.drop_index("ix_world_event_type", table_name="world_event", schema="worldsim")
    op.drop_index("ix_world_event_timeline", table_name="world_event", schema="worldsim")
    op.drop_table("world_event", schema="worldsim")
    op.drop_table("task_dependency", schema="worldsim")
    op.drop_table("request_budget_ledger", schema="worldsim")
    op.drop_table("model_call", schema="worldsim")
    op.drop_table("character_card_version", schema="worldsim")
    op.drop_table("task_run", schema="worldsim")
    op.drop_table("phase_snapshot", schema="worldsim")
    op.drop_table("location", schema="worldsim")
    op.drop_table("character", schema="worldsim")
    op.drop_index(
        "uq_world_config_one_active",
        table_name="world_config",
        schema="worldsim",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("world_config", schema="worldsim")
    op.drop_table("world_clock", schema="worldsim")
    op.drop_index(
        "uq_phase_run_one_nonterminal_per_world",
        table_name="phase_run",
        schema="worldsim",
        postgresql_where=sa.text("state NOT IN ('completed', 'failed', 'cancelled')"),
    )
    op.drop_table("phase_run", schema="worldsim")
    op.drop_index("ix_entity_world_type_name", table_name="entity", schema="worldsim")
    op.drop_index("ix_entity_world_lifecycle", table_name="entity", schema="worldsim")
    op.drop_table("entity", schema="worldsim")
    op.drop_table("aggregate_version", schema="worldsim")
    op.drop_index(
        "uq_world_one_live",
        table_name="world",
        schema="worldsim",
        postgresql_where=sa.text("status IN ('initializing', 'active', 'paused')"),
    )
    op.drop_table("world", schema="worldsim")
    op.drop_table("model_profile", schema="worldsim")
    # ### end Alembic commands ###
