"""Create Stage 1 action/scene/stream tables.

Revision ID: 0003_stage1_action_scene_tables
Revises: 0002_core_stage0_tables
Create Date: 2026-07-29
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003_stage1_action_scene_tables"
down_revision: str | None = "0002_core_stage0_tables"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scene",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("phase_run_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("scene_type", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column(
            "priority_score",
            sa.Numeric(precision=5, scale=4),
            server_default=sa.text("0.0000"),
            nullable=False,
        ),
        sa.Column(
            "priority_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("beat_budget", sa.SmallInteger(), nullable=False),
        sa.Column("high_impact", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("mutable_aggregate_ids", postgresql.ARRAY(sa.Uuid()), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "beat_budget >= 1 AND beat_budget <= 12", name=op.f("ck_scene_beat_budget_range")
        ),
        sa.CheckConstraint(
            "priority_score >= 0 AND priority_score <= 1",
            name=op.f("ck_scene_priority_score_range"),
        ),
        sa.CheckConstraint("version >= 0", name=op.f("ck_scene_version_nonneg")),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["worldsim.location.entity_id"],
            name=op.f("fk_scene_location_id_location"),
        ),
        sa.ForeignKeyConstraint(
            ["phase_run_id"],
            ["worldsim.phase_run.id"],
            name=op.f("fk_scene_phase_run_id_phase_run"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["worldsim.phase_snapshot.id"],
            name=op.f("fk_scene_snapshot_id_phase_snapshot"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_scene_idempotency_key")),
        schema="worldsim",
    )
    op.create_index(
        "ix_scene_phase_run", "scene", ["phase_run_id"], unique=False, schema="worldsim"
    )
    op.create_index("ix_scene_snapshot", "scene", ["snapshot_id"], unique=False, schema="worldsim")
    op.create_table(
        "action_proposal",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("phase_run_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_kind", sa.Text(), server_default=sa.text("'primary'"), nullable=False),
        sa.Column("action_family", sa.Text(), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("utterance", sa.Text(), nullable=True),
        sa.Column("target_location_id", sa.Uuid(), nullable=True),
        sa.Column("visibility", sa.Text(), nullable=False),
        sa.Column(
            "risk_tolerance",
            sa.Numeric(precision=5, scale=4),
            server_default=sa.text("0.5000"),
            nullable=False,
        ),
        sa.Column(
            "estimated_duration_phases",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("continuation_activity_id", sa.Uuid(), nullable=True),
        sa.Column(
            "desired_effects",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "fallback_action",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "validation_status", sa.Text(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_call_id", sa.Uuid(), nullable=True),
        sa.Column("generation", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "proposal_kind IN ('primary', 'fallback', 'continuation')",
            name=op.f("ck_action_proposal_proposal_kind"),
        ),
        sa.CheckConstraint(
            "validation_status IN ('pending', 'valid', 'invalid', 'rejected')",
            name=op.f("ck_action_proposal_validation_status"),
        ),
        sa.CheckConstraint(
            "estimated_duration_phases >= 1 AND estimated_duration_phases <= 240",
            name=op.f("ck_action_proposal_duration_range"),
        ),
        sa.CheckConstraint("generation >= 0", name=op.f("ck_action_proposal_generation_nonneg")),
        sa.CheckConstraint(
            "risk_tolerance >= 0 AND risk_tolerance <= 1",
            name=op.f("ck_action_proposal_risk_tolerance_range"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["worldsim.character.entity_id"],
            name=op.f("fk_action_proposal_actor_id_character"),
        ),
        sa.ForeignKeyConstraint(
            ["model_call_id"],
            ["worldsim.model_call.id"],
            name=op.f("fk_action_proposal_model_call_id_model_call"),
        ),
        sa.ForeignKeyConstraint(
            ["phase_run_id"],
            ["worldsim.phase_run.id"],
            name=op.f("fk_action_proposal_phase_run_id_phase_run"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["worldsim.phase_snapshot.id"],
            name=op.f("fk_action_proposal_snapshot_id_phase_snapshot"),
        ),
        sa.ForeignKeyConstraint(
            ["target_location_id"],
            ["worldsim.location.entity_id"],
            name=op.f("fk_action_proposal_target_location_id_location"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_proposal")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_action_proposal_idempotency_key")),
        schema="worldsim",
    )
    op.create_index(
        "ix_action_proposal_phase",
        "action_proposal",
        ["phase_run_id"],
        unique=False,
        schema="worldsim",
    )
    op.create_index(
        "ix_action_proposal_snapshot",
        "action_proposal",
        ["snapshot_id"],
        unique=False,
        schema="worldsim",
    )
    op.create_index(
        "uq_action_proposal_primary_actor_phase",
        "action_proposal",
        ["phase_run_id", "actor_id"],
        unique=True,
        schema="worldsim",
        postgresql_where=sa.text("proposal_kind = 'primary'"),
    )
    op.create_table(
        "narration",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=False),
        sa.Column("world_event_id", sa.Uuid(), nullable=False),
        sa.Column("perspective", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("source_kind", sa.Text(), nullable=False),
        sa.Column("model_call_id", sa.Uuid(), nullable=True),
        sa.Column("is_fallback", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_call_id"],
            ["worldsim.model_call.id"],
            name=op.f("fk_narration_model_call_id_model_call"),
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"], ["worldsim.scene.id"], name=op.f("fk_narration_scene_id_scene")
        ),
        sa.ForeignKeyConstraint(
            ["world_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_narration_world_event_id_world_event"),
        ),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_narration_world_id_world")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_narration")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_narration_idempotency_key")),
        sa.UniqueConstraint(
            "scene_id",
            "perspective",
            "content_hash",
            name=op.f("uq_narration_scene_id_perspective_content_hash"),
        ),
        schema="worldsim",
    )
    op.create_index(
        "ix_narration_scene", "narration", ["scene_id"], unique=False, schema="worldsim"
    )
    op.create_index(
        "ix_narration_world_event", "narration", ["world_event_id"], unique=False, schema="worldsim"
    )
    op.create_table(
        "scene_participant",
        sa.Column("scene_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("participant_role", sa.Text(), nullable=False),
        sa.Column(
            "reaction_eligible", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("knowledge_scope_hash", sa.Text(), nullable=True),
        sa.Column("joined_at_beat", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("left_at_beat", sa.SmallInteger(), nullable=True),
        sa.CheckConstraint(
            "joined_at_beat >= 0", name=op.f("ck_scene_participant_joined_beat_nonneg")
        ),
        sa.CheckConstraint(
            "left_at_beat IS NULL OR left_at_beat >= joined_at_beat",
            name=op.f("ck_scene_participant_left_beat_order"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["worldsim.entity.id"],
            name=op.f("fk_scene_participant_entity_id_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"], ["worldsim.scene.id"], name=op.f("fk_scene_participant_scene_id_scene")
        ),
        sa.PrimaryKeyConstraint("scene_id", "entity_id", name=op.f("pk_scene_participant")),
        schema="worldsim",
    )
    op.create_table(
        "scene_resolution",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=False),
        sa.Column("resolution_level", sa.Text(), nullable=False),
        sa.Column("accepted_attempt_ids", postgresql.ARRAY(sa.Uuid()), nullable=True),
        sa.Column(
            "rejected_assumptions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "proposed_effects",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "delayed_effects",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "observation_seeds",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "narration_constraints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "visual_significance",
            sa.Numeric(precision=5, scale=4),
            server_default=sa.text("0.0000"),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Numeric(precision=5, scale=4),
            server_default=sa.text("0.0000"),
            nullable=False,
        ),
        sa.Column("resolver_profile_id", sa.Uuid(), nullable=True),
        sa.Column("model_call_id", sa.Uuid(), nullable=True),
        sa.Column(
            "expected_aggregate_versions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "validation_status", sa.Text(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("commit_event_id", sa.Uuid(), nullable=True),
        sa.Column("canonical_summary", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "validation_status IN ('pending', 'valid', 'invalid', 'committed', 'rejected')",
            name=op.f("ck_scene_resolution_validation_status"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_scene_resolution_confidence_range")
        ),
        sa.CheckConstraint(
            "visual_significance >= 0 AND visual_significance <= 1",
            name=op.f("ck_scene_resolution_visual_significance_range"),
        ),
        sa.ForeignKeyConstraint(
            ["commit_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_scene_resolution_commit_event_id_world_event"),
        ),
        sa.ForeignKeyConstraint(
            ["model_call_id"],
            ["worldsim.model_call.id"],
            name=op.f("fk_scene_resolution_model_call_id_model_call"),
        ),
        sa.ForeignKeyConstraint(
            ["resolver_profile_id"],
            ["worldsim.model_profile.id"],
            name=op.f("fk_scene_resolution_resolver_profile_id_model_profile"),
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"], ["worldsim.scene.id"], name=op.f("fk_scene_resolution_scene_id_scene")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_resolution")),
        sa.UniqueConstraint("commit_event_id", name=op.f("uq_scene_resolution_commit_event_id")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_scene_resolution_idempotency_key")),
        sa.UniqueConstraint("scene_id", name=op.f("uq_scene_resolution_scene_id")),
        schema="worldsim",
    )
    op.create_table(
        "stream_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "fictional_time",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.Text(), server_default=sa.text("'1'"), nullable=False),
        sa.Column("phase_run_id", sa.Uuid(), nullable=True),
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("world_event_id", sa.Uuid(), nullable=True),
        sa.Column(
            "perspective_scope", sa.Text(), server_default=sa.text("'world'"), nullable=False
        ),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_stream_event_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["phase_run_id"],
            ["worldsim.phase_run.id"],
            name=op.f("fk_stream_event_phase_run_id_phase_run"),
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"], ["worldsim.scene.id"], name=op.f("fk_stream_event_scene_id_scene")
        ),
        sa.ForeignKeyConstraint(
            ["world_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_stream_event_world_event_id_world_event"),
        ),
        sa.ForeignKeyConstraint(
            ["world_id"], ["worldsim.world.id"], name=op.f("fk_stream_event_world_id_world")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stream_event")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_stream_event_idempotency_key")),
        sa.UniqueConstraint("world_id", "sequence", name=op.f("uq_stream_event_world_id_sequence")),
        schema="worldsim",
    )
    op.create_index(
        "ix_stream_event_type", "stream_event", ["event_type"], unique=False, schema="worldsim"
    )
    op.create_index(
        "ix_stream_event_world_seq",
        "stream_event",
        ["world_id", "sequence"],
        unique=False,
        schema="worldsim",
    )
    op.create_table(
        "action_target",
        sa.Column("action_proposal_id", sa.Uuid(), nullable=False),
        sa.Column("target_entity_id", sa.Uuid(), nullable=False),
        sa.Column("target_role", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_action_target_ordinal_nonneg")),
        sa.ForeignKeyConstraint(
            ["action_proposal_id"],
            ["worldsim.action_proposal.id"],
            name=op.f("fk_action_target_action_proposal_id_action_proposal"),
        ),
        sa.ForeignKeyConstraint(
            ["target_entity_id"],
            ["worldsim.entity.id"],
            name=op.f("fk_action_target_target_entity_id_entity"),
        ),
        sa.PrimaryKeyConstraint(
            "action_proposal_id", "target_entity_id", "target_role", name=op.f("pk_action_target")
        ),
        schema="worldsim",
    )
    op.create_table(
        "player_control_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.Column("controller_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("waiting_input", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("phase_run_id", sa.Uuid(), nullable=True),
        sa.Column("last_command_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("version", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'waiting_input', 'released', 'expired')",
            name=op.f("ck_player_control_session_player_control_status"),
        ),
        sa.CheckConstraint("version >= 0", name=op.f("ck_player_control_session_version_nonneg")),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["worldsim.character.entity_id"],
            name=op.f("fk_player_control_session_character_id_character"),
        ),
        sa.ForeignKeyConstraint(
            ["last_command_id"],
            ["worldsim.user_command.id"],
            name=op.f("fk_player_control_session_last_command_id_user_command"),
        ),
        sa.ForeignKeyConstraint(
            ["phase_run_id"],
            ["worldsim.phase_run.id"],
            name=op.f("fk_player_control_session_phase_run_id_phase_run"),
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worldsim.world.id"],
            name=op.f("fk_player_control_session_world_id_world"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_control_session")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_player_control_session_idempotency_key")
        ),
        schema="worldsim",
    )
    op.create_index(
        "ix_player_control_world",
        "player_control_session",
        ["world_id"],
        unique=False,
        schema="worldsim",
    )
    op.create_index(
        "uq_player_control_one_active_per_character",
        "player_control_session",
        ["character_id"],
        unique=True,
        schema="worldsim",
        postgresql_where=sa.text("status IN ('active', 'waiting_input')"),
    )
    op.create_table(
        "reaction_proposal",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=False),
        sa.Column("phase_run_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("triggering_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("reactor_id", sa.Uuid(), nullable=False),
        sa.Column("beat_index", sa.SmallInteger(), nullable=False),
        sa.Column("action_family", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("utterance", sa.Text(), nullable=True),
        sa.Column("target_entity_ids", postgresql.ARRAY(sa.Uuid()), nullable=True),
        sa.Column(
            "resource_intentions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "desired_outcomes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "validation_status", sa.Text(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_call_id", sa.Uuid(), nullable=True),
        sa.Column("source_kind", sa.Text(), server_default=sa.text("'model'"), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_kind IN ('model', 'deterministic', 'player', 'engine')",
            name=op.f("ck_reaction_proposal_source_kind"),
        ),
        sa.CheckConstraint(
            "validation_status IN ('pending', 'valid', 'invalid', 'rejected')",
            name=op.f("ck_reaction_proposal_validation_status"),
        ),
        sa.CheckConstraint(
            "beat_index >= 0 AND beat_index <= 12",
            name=op.f("ck_reaction_proposal_beat_index_range"),
        ),
        sa.ForeignKeyConstraint(
            ["model_call_id"],
            ["worldsim.model_call.id"],
            name=op.f("fk_reaction_proposal_model_call_id_model_call"),
        ),
        sa.ForeignKeyConstraint(
            ["phase_run_id"],
            ["worldsim.phase_run.id"],
            name=op.f("fk_reaction_proposal_phase_run_id_phase_run"),
        ),
        sa.ForeignKeyConstraint(
            ["reactor_id"],
            ["worldsim.character.entity_id"],
            name=op.f("fk_reaction_proposal_reactor_id_character"),
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"], ["worldsim.scene.id"], name=op.f("fk_reaction_proposal_scene_id_scene")
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["worldsim.phase_snapshot.id"],
            name=op.f("fk_reaction_proposal_snapshot_id_phase_snapshot"),
        ),
        sa.ForeignKeyConstraint(
            ["triggering_attempt_id"],
            ["worldsim.action_proposal.id"],
            name=op.f("fk_reaction_proposal_triggering_attempt_id_action_proposal"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reaction_proposal")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_reaction_proposal_idempotency_key")),
        sa.UniqueConstraint(
            "scene_id",
            "reactor_id",
            "beat_index",
            "triggering_attempt_id",
            name=op.f("uq_reaction_proposal_scene_id_reactor_id_beat_index_triggering_attempt_id"),
        ),
        schema="worldsim",
    )
    op.create_index(
        "ix_reaction_proposal_scene",
        "reaction_proposal",
        ["scene_id"],
        unique=False,
        schema="worldsim",
    )
    op.create_table(
        "scene_action",
        sa.Column("scene_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "role IN ('initiator', 'co_intent', 'conflicting_intent', 'background')",
            name=op.f("ck_scene_action_scene_action_role"),
        ),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_scene_action_ordinal_nonneg")),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["worldsim.action_proposal.id"],
            name=op.f("fk_scene_action_proposal_id_action_proposal"),
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"], ["worldsim.scene.id"], name=op.f("fk_scene_action_scene_id_scene")
        ),
        sa.PrimaryKeyConstraint("scene_id", "proposal_id", name=op.f("pk_scene_action")),
        schema="worldsim",
    )
    op.create_table(
        "scene_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=False),
        sa.Column("phase_run_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("beat_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("beat_budget", sa.SmallInteger(), nullable=False),
        sa.Column("high_impact", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("resolution_id", sa.Uuid(), nullable=True),
        sa.Column("committed_event_id", sa.Uuid(), nullable=True),
        sa.Column("attempt_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_scene_run_attempt_count_nonneg")),
        sa.CheckConstraint(
            "beat_budget >= 1 AND beat_budget <= 12", name=op.f("ck_scene_run_beat_budget_range")
        ),
        sa.CheckConstraint("beat_count >= 0", name=op.f("ck_scene_run_beat_count_nonneg")),
        sa.CheckConstraint("version >= 0", name=op.f("ck_scene_run_version_nonneg")),
        sa.ForeignKeyConstraint(
            ["committed_event_id"],
            ["worldsim.world_event.id"],
            name=op.f("fk_scene_run_committed_event_id_world_event"),
        ),
        sa.ForeignKeyConstraint(
            ["phase_run_id"],
            ["worldsim.phase_run.id"],
            name=op.f("fk_scene_run_phase_run_id_phase_run"),
        ),
        sa.ForeignKeyConstraint(
            ["resolution_id"],
            ["worldsim.scene_resolution.id"],
            name=op.f("fk_scene_run_resolution_id_scene_resolution"),
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"], ["worldsim.scene.id"], name=op.f("fk_scene_run_scene_id_scene")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_run")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_scene_run_idempotency_key")),
        sa.UniqueConstraint("scene_id", name=op.f("uq_scene_run_scene_id")),
        schema="worldsim",
    )
    op.create_index(
        "ix_scene_run_phase", "scene_run", ["phase_run_id"], unique=False, schema="worldsim"
    )
    op.create_foreign_key(
        op.f("fk_world_event_scene_id_scene"),
        "world_event",
        "scene",
        ["scene_id"],
        ["id"],
        source_schema="worldsim",
        referent_schema="worldsim",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_world_event_scene_id_scene"),
        "world_event",
        schema="worldsim",
        type_="foreignkey",
    )
    op.drop_index("ix_scene_run_phase", table_name="scene_run", schema="worldsim")
    op.drop_table("scene_run", schema="worldsim")
    op.drop_table("scene_action", schema="worldsim")
    op.drop_index("ix_reaction_proposal_scene", table_name="reaction_proposal", schema="worldsim")
    op.drop_table("reaction_proposal", schema="worldsim")
    op.drop_index(
        "uq_player_control_one_active_per_character",
        table_name="player_control_session",
        schema="worldsim",
        postgresql_where=sa.text("status IN ('active', 'waiting_input')"),
    )
    op.drop_index("ix_player_control_world", table_name="player_control_session", schema="worldsim")
    op.drop_table("player_control_session", schema="worldsim")
    op.drop_table("action_target", schema="worldsim")
    op.drop_index("ix_stream_event_world_seq", table_name="stream_event", schema="worldsim")
    op.drop_index("ix_stream_event_type", table_name="stream_event", schema="worldsim")
    op.drop_table("stream_event", schema="worldsim")
    op.drop_table("scene_resolution", schema="worldsim")
    op.drop_table("scene_participant", schema="worldsim")
    op.drop_index("ix_narration_world_event", table_name="narration", schema="worldsim")
    op.drop_index("ix_narration_scene", table_name="narration", schema="worldsim")
    op.drop_table("narration", schema="worldsim")
    op.drop_index(
        "uq_action_proposal_primary_actor_phase",
        table_name="action_proposal",
        schema="worldsim",
        postgresql_where=sa.text("proposal_kind = 'primary'"),
    )
    op.drop_index("ix_action_proposal_snapshot", table_name="action_proposal", schema="worldsim")
    op.drop_index("ix_action_proposal_phase", table_name="action_proposal", schema="worldsim")
    op.drop_table("action_proposal", schema="worldsim")
    op.drop_index("ix_scene_snapshot", table_name="scene", schema="worldsim")
    op.drop_index("ix_scene_phase_run", table_name="scene", schema="worldsim")
    op.drop_table("scene", schema="worldsim")
    # ### end Alembic commands ###
